import nanoled from "../assets/bestseller/class-nano-led.avif";
import fitboot from "../assets/bestseller/sdk-portable-bt.avif";
import jpgaming from "../assets/bestseller/jpgaming-laptop.avif";
import shelled from "../assets/bestseller/shel-50-led.avif";
import zpixel from "../assets/bestseller/zpixel-max.avif";

// Tablets
import corrplaytime from "../assets/tablets/corr-playtime.avif";
import jpstablet from "../assets/tablets/jp-space-tablet.avif";
import oceanpro from "../assets/tablets/ocean-pro11.avif";
import tabletfdplus from "../assets/tablets/ove-tabletfd-plus.avif";
import pilatesgo from "../assets/tablets/pilates-go10.5.avif";
import sheerpro from "../assets/tablets/sheer-pro7.9.avif";
import sheertablet from "../assets/tablets/sheer-tablet.avif";
import spacetablet from "../assets/tablets/space-tablet-s7.avif";

// Drones & Cameras
import drone from "../assets/drones&cameras/exe-mini-drone.avif";
import camera1 from "../assets/drones&cameras/h1c-indoor-wireless.avif";
import drone2 from "../assets/drones&cameras/hkitech-quadcopter.avif";
import camera2 from "../assets/drones&cameras/megapixel-waterproof.avif";
import camera3 from "../assets/drones&cameras/pantony-180-20.0.avif";
import camera5 from "../assets/drones&cameras/pantony-dslr-old.avif";
import drone3 from "../assets/drones&cameras/wave-mini4.avif";
import camera4 from "../assets/drones&cameras/shak-outdoor.avif";

// Headphones
import headphone1 from "../assets/headphones/balo-headphones.avif";
import headphone2 from "../assets/headphones/certified-pantony-buds.avif";
import headphone3 from "../assets/headphones/drums-pro-wireless.avif";
import headphone4 from "../assets/headphones/inears-noise-cancellation.avif";
import headphone5 from "../assets/headphones/mx50-wired.avif";
import headphone6 from "../assets/headphones/space-buds.avif";
import headphone7 from "../assets/headphones/surround-sound-10.2.avif";
import headphone8 from "../assets/headphones/white-buds-wireless.avif";

// speakers
import speaker1 from "../assets/speakers/pill-shape-bt.avif";
import speaker2 from "../assets/speakers/round-mini-bt.avif";
import speaker3 from "../assets/speakers/sdk-portable-bt.avif";
import speaker4 from "../assets/speakers/sdkmini-portable-bt.avif";
import speaker5 from "../assets/speakers/studio8-portable-bt.avif";
import speaker6 from "../assets/speakers/turn5-portable-handle.avif";
import speaker7 from "../assets/speakers/turn5-portable-speaker.avif";
import speaker8 from "../assets/speakers/tvbt-soundbar.avif";

// Mobiles
import mobile1 from "../assets/mobile/jp-exmax.avif";
import mobile2 from "../assets/mobile/jplight-phantom.avif";
import mobile3 from "../assets/mobile/max-pantony.avif";
import mobile4 from "../assets/mobile/ove-light.avif";
import mobile5 from "../assets/mobile/pantony-super.avif";
import mobile6 from "../assets/mobile/pantony-x21.avif";
import mobile7 from "../assets/mobile/xpd-protector.avif";
import mobile8 from "../assets/mobile/zpixel-max.avif";

// Tvcinemas
import homcinema1 from "../assets/tv&cinema/allure-55-led.avif";
import homcinema2 from "../assets/tv&cinema/class-42-streamer.avif";
import homcinema3 from "../assets/tv&cinema/class-nano-led.avif";
import homcinema4 from "../assets/tv&cinema/jp-470-projector.avif";
import homcinema5 from "../assets/tv&cinema/shel-40-led.avif";
import homcinema6 from "../assets/tv&cinema/shel-50-led.avif";
import homcinema7 from "../assets/tv&cinema/tv-bt-soundbar.avif";
import homcinema8 from "../assets/tv&cinema/wilsom-home-cinema.avif";

// Werables
import wearables1 from "../assets/werables tech/fitboot-inspire.avif";
import wearables2 from "../assets/werables tech/fitwatch-fitness.avif";
import wearables3 from "../assets/werables tech/fitwatch-xdh.avif";
import wearables4 from "../assets/werables tech/hv-virtual.avif";
import wearables5 from "../assets/werables tech/journey-glass-xd.avif";
import wearables6 from "../assets/werables tech/pantony-6p.avif";
import wearables7 from "../assets/werables tech/safay-gen.avif";
import wearables8 from "../assets/werables tech/space-moon.avif";

const ProductsData = [
  // ============================
  // 1. COMPUTERS (10)
  // ============================
  {
    id: 1,
    name: "UltraPro Laptop X1",
    oldprice: 82000,
    Price: 79999,
    image: nanoled,
    sale: true,
    Bestseller: true,
    category: "Computers",
    productInfo: "16GB RAM • 512GB SSD • Intel i7",
    description: "A reliable power-packed laptop built for performance.",
  },
  {
    id: 2,
    name: "SpeedMaster Gaming PC",
    oldprice: 95000,
    Price: 89999,
    image: fitboot,
    sale: false,
    Bestseller: true,
    category: "Computers",
    productInfo: "RTX 3060 • 16GB RAM • 1TB SSD",
    description: "A gaming tower engineered for smooth gameplay.",
  },
  {
    id: 3,
    name: "ThinkPro Business Laptop",
    oldprice: 70000,
    Price: 66999,
    image: fitboot,
    sale: true,
    Bestseller: true,
    category: "Computers",
    productInfo: "8GB RAM • 512GB SSD",
    description: "Compact business laptop ideal for office workflows.",
  },
  {
    id: 4,
    name: "VisionTab All-in-One PC",
    oldprice: 58000,
    Price: 54999,
    image: jpgaming,
    sale: false,
    Bestseller: false,
    category: "Computers",
    productInfo: "24-inch • 8GB RAM • 1TB HDD",
    description: "All-in-one desktop for home and office use.",
  },
  {
    id: 5,
    name: "NanoEdge Laptop",
    oldprice: 52000,
    Price: 49999,
    image: shelled,
    sale: false,
    Bestseller: false,
    category: "Computers",
    productInfo: "8GB RAM • 256GB SSD",
    description: "Slim laptop perfect for students.",
  },
  {
    id: 6,
    name: "CreatorPad Workstation",
    oldprice: 140000,
    Price: 134999,
    image: zpixel,
    sale: true,
    Bestseller: true,
    category: "Computers",
    productInfo: "RTX 4070 • 32GB RAM",
    description: "Engineering workstation for rendering & editing.",
  },
  {
    id: 7,
    name: "MiniCube PC",
    oldprice: 35000,
    Price: 32999,
    image: oceanpro,
    sale: false,
    Bestseller: false,
    category: "Computers",
    productInfo: "Small Form Factor • 8GB RAM",
    description: "A compact PC suitable for home-office setups.",
  },
  {
    id: 8,
    name: "ProDesk S2",
    oldprice: 65000,
    Price: 62999,
    image: zpixel,
    sale: true,
    Bestseller: true,
    category: "Computers",
    productInfo: "16GB RAM • 512GB SSD",
    description: "Office-ready machine with strong multitasking ability.",
  },
  // {
  //   id: 9,
  //   name: "StudentBook Lite",
  //   oldprice: 30000,
  //   Price: 27999,
  //   image: "studentbook-lite.jpg",
  //   sale: true,
  //   Bestseller: false,
  //   category: "Computers",
  //   productInfo: "4GB RAM • 128GB SSD",
  //   description: "Affordable student laptop with essential features.",
  // },
  // {
  //   id: 10,
  //   name: "PrimeBook X",
  //   oldprice: 48000,
  //   Price: 45999,
  //   image: "primebook-x.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Computers",
  //   productInfo: "8GB RAM • 256GB SSD",
  //   description: "A stylish and efficient everyday laptop.",
  // },

  // ============================
  // 2. TABLETS (10)
  // ============================
  {
    id: 11,
    name: "TabPlus 10.5",
    oldprice: 28000,
    Price: 25999,
    image: corrplaytime,
    sale: false,
    Bestseller: false,
    category: "Tablets",
    productInfo: "10.5-inch • 128GB Storage",
    description: "A sleek tablet for entertainment and study.",
  },
  {
    id: 12,
    name: "EduTab 8",
    oldprice: 15000,
    Price: 12999,
    image: jpstablet,
    sale: false,
    Bestseller: false,
    category: "Tablets",
    productInfo: "8-inch • 64GB Storage",
    description: "Perfect for school students and reading.",
  },
  {
    id: 13,
    name: "ProDraw Tablet",
    oldprice: 45000,
    Price: 42999,
    image: oceanpro,
    sale: false,
    Bestseller: true,
    category: "Tablets",
    productInfo: "Stylus Support • 256GB Storage",
    description: "Tablet designed for artists and designers.",
  },
  {
    id: 14,
    name: "GameTab X",
    oldprice: 35000,
    Price: 32999,
    image: tabletfdplus,
    sale: false,
    Bestseller: true,
    category: "Tablets",
    productInfo: "High Refresh Display • 128GB",
    description: "Gaming-ready tablet with smooth graphics.",
  },
  {
    id: 15,
    name: "MegaTab 12",
    oldprice: 60000,
    Price: 56999,
    image: pilatesgo,
    sale: true,
    Bestseller: true,
    category: "Tablets",
    productInfo: "12-inch • 256GB • Premium Build",
    description: "Large tablet ideal for movies and productivity.",
  },
  {
    id: 16,
    name: "KidsTab Fun",
    oldprice: 12000,
    Price: 10999,
    image: sheerpro,
    sale: false,
    Bestseller: false,
    category: "Tablets",
    productInfo: "Child Mode • Durable Body",
    description: "A safe and fun tablet for kids.",
  },
  {
    id: 17,
    name: "OfficeTab S",
    oldprice: 25000,
    Price: 23999,
    image: sheertablet,
    sale: false,
    Bestseller: false,
    category: "Tablets",
    productInfo: "10-inch • 64GB",
    description: "Affordable tablet for office & home use.",
  },
  {
    id: 18,
    name: "SlimTab Air",
    oldprice: 38000,
    Price: 35999,
    image: spacetablet,
    sale: true,
    Bestseller: false,
    category: "Tablets",
    productInfo: "Ultra Thin • 128GB",
    description: "Portable slim tablet with long battery life.",
  },
  // {
  //   id: 19,
  //   name: "StudyMate Tab",
  //   oldprice: 19000,
  //   Price: 17999,
  //   image: "studymate-tab.jpg",
  //   sale: false,
  //   Bestseller: true,
  //   category: "Tablets",
  //   productInfo: "Education Apps • Eye Protection",
  //   description: "Specially designed for online learning.",
  // },
  // {
  //   id: 20,
  //   name: "EliteTab Pro",
  //   oldprice: 80000,
  //   Price: 76999,
  //   image: "elitetab-pro.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Tablets",
  //   productInfo: "12.9-inch • 512GB • Flagship",
  //   description: "High-end professional tablet for creators.",
  // },

  // ============================
  // 3. DRONES (10)
  // ============================
  {
    id: 21,
    name: "SkyView Drone 4K",
    oldprice: 22000,
    Price: 19999,
    image: drone,
    sale: false,
    Bestseller: true,
    category: "Drones",
    productInfo: "4K Camera • 25 min Flight",
    description: "Capture sharp aerial shots with this 4K drone.",
  },
  {
    id: 22,
    name: "MiniFly Drone",
    oldprice: 9000,
    Price: 7999,
    image: drone2,
    sale: false,
    Bestseller: false,
    category: "Drones",
    productInfo: "Beginner Friendly",
    description: "Easy-to-operate mini drone for kids and newbies.",
  },
  {
    id: 23,
    name: "RacerX Drone",
    oldprice: 30000,
    Price: 27999,
    image: drone3,
    sale: false,
    Bestseller: true,
    category: "Drones",
    productInfo: "High Speed • FPV Mode",
    description: "A drone built for racing and fast flying.",
  },
  {
    id: 24,
    name: "ProShot 8K",
    oldprice: 60000,
    Price: 57999,
    image: camera1,
    sale: false,
    Bestseller: true,
    category: "Drones",
    productInfo: "8K Camera • GPS",
    description: "Professional-grade drone for creators.",
  },
  {
    id: 25,
    name: "TravelFold ",
    oldprice: 18000,
    Price: 16999,
    image: camera2,
    sale: false,
    Bestseller: false,
    category: "Drones",
    productInfo: "Foldable • Portable",
    description: "Perfect drone for travellers.",
  },
  {
    id: 26,
    name: "NightVision ",
    oldprice: 35000,
    Price: 32999,
    image: camera3,
    sale: true,
    Bestseller: true,
    category: "Drones",
    productInfo: "Night Mode • Long Range",
    description: "Fly safely even in low light conditions.",
  },
  {
    id: 27,
    name: "Beginner S1",
    oldprice: 12000,
    Price: 10999,
    image: camera4,
    sale: false,
    Bestseller: false,
    category: "Drones",
    productInfo: "Auto Hover • Safe Mode",
    description: "Perfect first drone for learners.",
  },
  {
    id: 28,
    name: "AeroCam Drone",
    oldprice: 25000,
    Price: 23999,
    image: camera5,
    sale: false,
    Bestseller: true,
    category: "Drones",
    productInfo: "4K Camera • GPS Stabilization",
    description: "Drone with smooth camera and stability.",
  },
  // {
  //   id: 29,
  //   name: "Selfie Drone Mini",
  //   oldprice: 15000,
  //   Price: 13999,
  //   image: "selfie-drone-mini.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Drones",
  //   productInfo: "Auto Selfie • Gesture Control",
  //   description: "Pocket drone for quick selfies.",
  // },
  // {
  //   id: 30,
  //   name: "Industrial Drone X2",
  //   oldprice: 120000,
  //   Price: 114999,
  //   image: "industrial-drone-x2.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Drones",
  //   productInfo: "Heavy Duty • Inspection",
  //   description: "A drone built for industry and surveying.",
  // },

  // ============================
  // 4. CAMERAS (10)
  // ============================
  // {
  //   id: 31,
  //   name: "Ocean Pro 11",
  //   oldprice: 1500,
  //   Price: 1499,
  //   image: "ocean-pro-11.jpg",
  //   sale: true,
  //   Bestseller: false,
  //   category: "Cameras",
  //   productInfo: "Waterproof Mini Camera",
  //   description: "A compact waterproof digital camera.",
  // },
  // {
  //   id: 32,
  //   name: "PixelShot 4K Camera",
  //   oldprice: 25000,
  //   Price: 22999,
  //   image: "pixelshot-4k.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Cameras",
  //   productInfo: "4K Recording",
  //   description: "Capture sharp videos and photos.",
  // },
  // {
  //   id: 33,
  //   name: "ZoomPro DSLR",
  //   oldprice: 55000,
  //   Price: 52999,
  //   image: "zoompro-dslr.jpg",
  //   sale: false,
  //   Bestseller: true,
  //   category: "Cameras",
  //   productInfo: "24MP Sensor",
  //   description: "Ideal DSLR for photography beginners.",
  // },
  // {
  //   id: 34,
  //   name: "ActionCam HeroX",
  //   oldprice: 18000,
  //   Price: 16999,
  //   image: "actioncam-herox.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Cameras",
  //   productInfo: "Waterproof • 4K",
  //   description: "Adventure-ready action camera.",
  // },
  // {
  //   id: 35,
  //   name: "LiteCam Compact",
  //   oldprice: 10000,
  //   Price: 8999,
  //   image: "litecam-compact.jpg",
  //   sale: true,
  //   Bestseller: false,
  //   category: "Cameras",
  //   productInfo: "16MP • Pocket Size",
  //   description: "Simple compact camera for travel.",
  // },
  // {
  //   id: 36,
  //   name: "ProStudio Camera",
  //   oldprice: 95000,
  //   Price: 89999,
  //   image: "prostudio-camera.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Cameras",
  //   productInfo: "Professional 8K Camera",
  //   description: "Studio-grade camera for creators.",
  // },
  // {
  //   id: 37,
  //   name: "NightLens Camera",
  //   oldprice: 40000,
  //   Price: 37999,
  //   image: "nightlens-camera.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Cameras",
  //   productInfo: "Low Light Sensor",
  //   description: "Excellent camera for night photography.",
  // },
  // {
  //   id: 38,
  //   name: "TravelShot Camera",
  //   oldprice: 16000,
  //   Price: 14999,
  //   image: "travelshot-camera.jpg",
  //   sale: true,
  //   Bestseller: false,
  //   category: "Cameras",
  //   productInfo: "Lightweight • 20MP",
  //   description: "Perfect for capturing travel memories.",
  // },
  // {
  //   id: 39,
  //   name: "MaxPro Cam",
  //   oldprice: 12000,
  //   Price: 10999,
  //   image: "maxpro-cam.jpg",
  //   sale: false,
  //   Bestseller: true,
  //   category: "Cameras",
  //   productInfo: "HD Recording",
  //   description: "Budget-friendly HD camera.",
  // },
  // {
  //   id: 40,
  //   name: "SkyLens Drone Camera",
  //   oldprice: 35000,
  //   Price: 33999,
  //   image: "skylens-drone-camera.jpg",
  //   sale: true,
  //   Bestseller: false,
  //   category: "Cameras",
  //   productInfo: "Aerial Capture",
  //   description: "Aerial camera for drones and recording.",
  // },

  // ============================
  // 5. HEADPHONES (10)
  // ============================
  {
    id: 41,
    name: "BassBoost Headphones",
    oldprice: 1999,
    Price: 1499,
    image: headphone1,
    sale: true,
    Bestseller: true,
    category: "Headphone",
    productInfo: "Deep Bass • Wireless",
    description: "Wireless headphones with enhanced bass.",
  },
  {
    id: 42,
    name: "QuietPod ANC",
    oldprice: 3999,
    Price: 3599,
    image: headphone2,
    sale: false,
    Bestseller: true,
    category: "Headphone",
    productInfo: "Active Noise Cancellation",
    description: "Noise-cancelling headphones for focus.",
  },
  {
    id: 43,
    name: "ProStudio Headset   ",
    oldprice: 799,
    Price: 699,
    image: headphone3,
    sale: false,
    Bestseller: false,
    category: "Headphone",
    productInfo: "Comfort Fit",
    description: "Wired headphones suitable for daily use.",
  },
  {
    id: 44,
    name: "SportFlex Earbuds",
    oldprice: 1299,
    Price: 1199,
    image: headphone4,
    sale: true,
    Bestseller: false,
    category: "Headphone",
    productInfo: "Sweatproof • Wireless",
    description: "Perfect earbuds for gym and workouts.",
  },
  {
    id: 45,
    name: "LiteBeat Wired",
    oldprice: 4999,
    Price: 4599,
    image: headphone5,
    sale: false,
    Bestseller: true,
    category: "Headphone",
    productInfo: "Studio Quality",
    description: "Professional headset for editing and mixing.",
  },
  {
    id: 46,
    name: "MiniPods Wireless",
    oldprice: 2500,
    Price: 2299,
    image: headphone6,
    sale: false,
    Bestseller: true,
    category: "Headphone",
    productInfo: "Long Battery",
    description: "Compact earbuds with great battery backup.",
  },
  {
    id: 47,
    name: "FlexBass Gaming",
    oldprice: 3500,
    Price: 3299,
    image: headphone7,
    sale: false,
    Bestseller: false,
    category: "Headphone",
    productInfo: "Surround Sound",
    description: "Gaming headphones with deep sound effects.",
  },
  {
    id: 48,
    name: "Earpod Apple",
    oldprice: 999,
    Price: 899,
    image: headphone8,
    sale: false,
    Bestseller: false,
    category: "Headphone",
    productInfo: "Clear Audio",
    description: "Affordable headphones with crisp sound.",
  },
  // {
  //   id: 49,
  //   name: "Ultra ANC Pro",
  //   oldprice: 5999,
  //   Price: 5499,
  //   image: "ultra-anc-pro.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Headphone",
  //   productInfo: "Premium ANC",
  //   description: "Noise-cancelling flagship headphones.",
  // },
  // {
  //   id: 50,
  //   name: "Bloombuds Lite",
  //   oldprice: 1499,
  //   Price: 1399,
  //   image: "bloombuds-lite.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Headphone",
  //   productInfo: "Wireless",
  //   description: "Simple earbuds for casual users.",
  // },

  // ============================
  // 6. SPEAKERS (10)
  // ============================
  {
    id: 51,
    name: "BoomBox Mini",
    oldprice: 1999,
    Price: 1599,
    image: speaker1,
    sale: false,
    Bestseller: true,
    category: "Speaker",
    productInfo: "Portable • Bluetooth",
    description: "Compact Bluetooth speaker for outdoor fun.",
  },
  {
    id: 52,
    name: "ThunderBass Speaker",
    oldprice: 3500,
    Price: 3299,
    image: speaker2,
    sale: false,
    Bestseller: true,
    category: "Speaker",
    productInfo: "Deep Bass",
    description: "Powerful speaker with punchy bass.",
  },
  {
    id: 53,
    name: "StudioTune Soundbar",
    oldprice: 8000,
    Price: 7799,
    image: speaker3,
    sale: false,
    Bestseller: true,
    category: "Speaker",
    productInfo: "Home Theater",
    description: "Soundbar for cinema-like audio.",
  },
  {
    id: 54,
    name: "PartyBox XL",
    oldprice: 12000,
    Price: 11500,
    image: speaker4,
    sale: false,
    Bestseller: false,
    category: "Speaker",
    productInfo: "RGB • Loud",
    description: "Large speaker for parties and gatherings.",
  },
  {
    id: 55,
    name: "MiniPod Speaker",
    oldprice: 999,
    Price: 899,
    image: speaker5,
    sale: false,
    Bestseller: false,
    category: "Speaker",
    productInfo: "Portable",
    description: "Affordable mini speaker.",
  },
  {
    id: 56,
    name: "DolbyX Speaker",
    oldprice: 6500,
    Price: 6299,
    image: speaker6,
    sale: true,
    Bestseller: true,
    category: "Speaker",
    productInfo: "Dolby Audio",
    description: "High clarity Dolby-enabled speaker.",
  },
  {
    id: 57,
    name: "WaveSound Bar",
    oldprice: 4000,
    Price: 3799,
    image: speaker7,
    sale: false,
    Bestseller: false,
    category: "Speaker",
    productInfo: "Slim Design",
    description: "Slim bar speaker suitable for TVs.",
  },
  {
    id: 58,
    name: "SoundBoost Pro",
    oldprice: 5000,
    Price: 4799,
    image: speaker8,
    sale: true,
    Bestseller: false,
    category: "Speaker",
    productInfo: "Enhanced Sound",
    description: "High-output portable speaker.",
  },
  // {
  //   id: 59,
  //   name: "MegaParty Speaker",
  //   oldprice: 15000,
  //   Price: 13999,
  //   image: "megaparty-speaker.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Speaker",
  //   productInfo: "200W Output",
  //   description: "Powerful speaker for large gatherings.",
  // },
  // {
  //   id: 60,
  //   name: "CompactBeat Speaker",
  //   oldprice: 1200,
  //   Price: 1099,
  //   image: "compactbeat-speaker.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Speaker",
  //   productInfo: "Mini Bluetooth",
  //   description: "Tiny speaker with impressive sound.",
  // },

  // ============================
  // 7. MOBILE (10)
  // ============================
  {
    id: 61,
    name: "ZPixel Max",
    oldprice: 34999,
    Price: 29999,
    image: mobile1,
    sale: false,
    Bestseller: true,
    category: "Mobile",
    productInfo: "128GB • 50MP",
    description: "A fast and feature-packed smartphone.",
  },
  {
    id: 62,
    name: "AeroPhone S12",
    oldprice: 28000,
    Price: 25999,
    image: mobile2,
    sale: true,
    Bestseller: false,
    category: "Mobile",
    productInfo: "108MP Camera",
    description: "Smartphone with flagship camera.",
  },
  {
    id: 63,
    name: "LiteOne M2",
    oldprice: 15000,
    Price: 13999,
    image: mobile3,
    sale: false,
    Bestseller: false,
    category: "Mobile",
    productInfo: "6GB RAM",
    description: "Affordable phone with modern features.",
  },
  {
    id: 64,
    name: "SpeedX 5G",
    oldprice: 32000,
    Price: 29999,
    image: mobile4,
    sale: false,
    Bestseller: true,
    category: "Mobile",
    productInfo: "5G Chipset • 8GB RAM",
    description: "Fast 5G smartphone for multitasking.",
  },
  {
    id: 65,
    name: "SelfieMaster X",
    oldprice: 20000,
    Price: 18999,
    image: mobile5,
    sale: false,
    Bestseller: false,
    category: "Mobile",
    productInfo: "32MP Selfie",
    description: "Perfect phone for selfie lovers.",
  },
  {
    id: 66,
    name: "MegaBattery Pro",
    oldprice: 22000,
    Price: 20999,
    image: mobile6,
    sale: false,
    Bestseller: true,
    category: "Mobile",
    productInfo: "6000mAh Battery",
    description: "Long battery backup for heavy users.",
  },
  {
    id: 67,
    name: "GamerPhone FX",
    oldprice: 28000,
    Price: 26999,
    image: mobile7,
    sale: false,
    Bestseller: true,
    category: "Mobile",
    productInfo: "Gaming Mode",
    description: "Optimized for mobile gamers.",
  },
  {
    id: 68,
    name: "PrimePhone A8",
    oldprice: 18000,
    Price: 16999,
    image: mobile8,
    sale: false,
    Bestseller: false,
    category: "Mobile",
    productInfo: "Quad Camera",
    description: "Stylish smartphone with quad camera setup.",
  },
  // {
  //   id: 69,
  //   name: "NotePlus K10",
  //   oldprice: 25000,
  //   Price: 23999,
  //   image: "noteplus-k10.jpg",
  //   sale: true,
  //   Bestseller: false,
  //   category: "Mobile",
  //   productInfo: "Large Display",
  //   description: "Big display for media lovers.",
  // },
  // {
  //   id: 70,
  //   name: "EcoPhone Mini",
  //   oldprice: 10000,
  //   Price: 8999,
  //   image: "ecophone-mini.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Mobile",
  //   productInfo: "Compact Size",
  //   description: "Small-sized phone with essential features.",
  // },

  // ============================
  // 8. TV (10)
  // ============================
  // {
  //   id: 71,
  //   name: "SmartVision 50-inch",
  //   oldprice: 40000,
  //   Price: 37999,
  //   image: "smartvision-50.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "TV",
  //   productInfo: "4K UHD",
  //   description: "Crisp 4K television for home entertainment.",
  // },
  // {
  //   id: 72,
  //   name: "NanoLED 65",
  //   oldprice: 70000,
  //   Price: 66999,
  //   image: "nanoled-65.jpg",
  //   sale: true,
  //   Bestseller: false,
  //   category: "TV",
  //   productInfo: "NanoLED Display",
  //   description: "Bright and vivid NanoLED television.",
  // },
  // {
  //   id: 73,
  //   name: "UltraHD 43-inch",
  //   oldprice: 30000,
  //   Price: 27999,
  //   image: "ultrahd-43.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "TV",
  //   productInfo: "Full HD",
  //   description: "Budget-friendly TV for small rooms.",
  // },
  // {
  //   id: 74,
  //   name: "CinemaPro 75",
  //   oldprice: 120000,
  //   Price: 112999,
  //   image: "cinemapro-75.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "TV",
  //   productInfo: "75-inch • 4K",
  //   description: "Cinematic home-viewing experience.",
  // },
  // {
  //   id: 75,
  //   name: "SlimTV 32",
  //   oldprice: 18000,
  //   Price: 16999,
  //   image: "slimtv-32.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "TV",
  //   productInfo: "HD Ready",
  //   description: "Compact TV for bedrooms.",
  // },
  // {
  //   id: 76,
  //   name: "CrystalVision 55",
  //   oldprice: 60000,
  //   Price: 57999,
  //   image: "crystalvision-55.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "TV",
  //   productInfo: "4K HDR",
  //   description: "Immersive HDR display.",
  // },
  // {
  //   id: 77,
  //   name: "AndroidTV 40",
  //   oldprice: 26000,
  //   Price: 24999,
  //   image: "androidtv-40.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "TV",
  //   productInfo: "Smart TV",
  //   description: "Android-powered smart television.",
  // },
  // {
  //   id: 78,
  //   name: "MegaScreen 85",
  //   oldprice: 250000,
  //   Price: 239999,
  //   image: "megascreen-85.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "TV",
  //   productInfo: "85-inch • Premium",
  //   description: "Huge screen for luxury setups.",
  // },
  // {
  //   id: 79,
  //   name: "LiteTV 24",
  //   oldprice: 12000,
  //   Price: 10999,
  //   image: "litetv-24.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "TV",
  //   productInfo: "HD Ready",
  //   description: "Small size TV for kitchen or shop.",
  // },
  // {
  //   id: 80,
  //   name: "OLEDMaster 65",
  //   oldprice: 180000,
  //   Price: 169999,
  //   image: "oledmaster-65.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "TV",
  //   productInfo: "OLED • 4K",
  //   description: "Top quality OLED television.",
  // },

  // ============================
  // 9. HOMECINEMAS (10)
  // ============================
  {
    id: 81,
    name: "CineBox 5.1",
    oldprice: 20000,
    Price: 18999,
    image: homcinema1,
    sale: false,
    Bestseller: true,
    category: "Homecinemas",
    productInfo: "5.1 Surround",
    description: "Home theatre system with powerful bass.",
  },
  {
    id: 82,
    name: "SoundWave 7.1",
    oldprice: 30000,
    Price: 27999,
    image: homcinema2,
    sale: false,
    Bestseller: true,
    category: "Homecinemas",
    productInfo: "7.1 Surround",
    description: "Premium home sound setup.",
  },
  {
    id: 83,
    name: "MiniTheater",
    oldprice: 15000,
    Price: 13999,
    image: homcinema3,
    sale: false,
    Bestseller: false,
    category: "Homecinemas",
    productInfo: "Compact Setup",
    description: "Small home theater for bedrooms.",
  },
  {
    id: 84,
    name: "DolbyBar X",
    oldprice: 18000,
    Price: 16999,
    image: homcinema4,
    sale: true,
    Bestseller: false,
    category: "Homecinemas",
    productInfo: "Dolby Audio",
    description: "Soundbar with Dolby clarity.",
  },
  {
    id: 85,
    name: "MegaCinema Pro",
    oldprice: 50000,
    Price: 46999,
    image: homcinema5,
    sale: false,
    Bestseller: true,
    category: "Homecinemas",
    productInfo: "High Power",
    description: "Premium setup for a cinematic experience.",
  },
  {
    id: 86,
    name: "BassBoom 2.1",
    oldprice: 12000,
    Price: 10999,
    image: homcinema6,
    sale: false,
    Bestseller: false,
    category: "Homecinemas",
    productInfo: "2.1 Channel",
    description: "Budget-friendly setup for casual users.",
  },
  {
    id: 87,
    name: "SurroundX 360",
    oldprice: 25000,
    Price: 23999,
    image: homcinema7,
    sale: false,
    Bestseller: false,
    category: "Homecinemas",
    productInfo: "360° Sound",
    description: "Multi-direction audio output.",
  },
  {
    id: 88,
    name: "CinemaBlast Max",
    oldprice: 40000,
    Price: 38999,
    image: homcinema8,
    sale: false,
    Bestseller: true,
    category: "Homecinemas",
    productInfo: "High Output",
    description: "Loud and powerful home cinema.",
  },
  // {
  //   id: 89,
  //   name: "HomeTheater Lite",
  //   oldprice: 10000,
  //   Price: 9499,
  //   image: "hometheater-lite.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Homecinemas",
  //   productInfo: "Basic",
  //   description: "Affordable entry-level home theater.",
  // },
  // {
  //   id: 90,
  //   name: "CinemaPro Studio",
  //   oldprice: 65000,
  //   Price: 62999,
  //   image: "cinemapro-studio.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Homecinemas",
  //   productInfo: "Professional Setup",
  //   description: "Studio-grade home cinema system.",
  // },

  // ============================
  // 10. WEARABLES (10)
  // ============================
  {
    id: 91,
    name: "FitBand Pro",
    oldprice: 3000,
    Price: 2799,
    image: wearables1,
    sale: false,
    Bestseller: true,
    category: "Wearables",
    productInfo: "Heart Rate Monitor",
    description: "Fitness tracker for daily health monitoring.",
  },
  {
    id: 92,
    name: "SmartWatch Z2",
    oldprice: 4500,
    Price: 4299,
    image: wearables2,
    sale: true,
    Bestseller: true,
    category: "Wearables",
    productInfo: "Calling • AMOLED",
    description: "Smartwatch with Bluetooth calling.",
  },
  {
    id: 93,
    name: "RunBand Lite",
    oldprice: 1800,
    Price: 1599,
    image: wearables3,
    sale: false,
    Bestseller: false,
    category: "Wearables",
    productInfo: "Step Counter",
    description: "Lightweight band for joggers.",
  },
  {
    id: 94,
    name: "HealthWatch X",
    oldprice: 5000,
    Price: 4799,
    image: wearables4,
    sale: false,
    Bestseller: true,
    category: "Wearables",
    productInfo: "SpO2 + Heart Rate",
    description: "Smartwatch with advanced health tracking.",
  },
  {
    id: 95,
    name: "KidWatch Fun",
    oldprice: 2000,
    Price: 1899,
    image: wearables5,
    sale: false,
    Bestseller: false,
    category: "Wearables",
    productInfo: "GPS Tracking",
    description: "Safe smartwatch designed for kids.",
  },
  {
    id: 96,
    name: "GymTracker G1",
    oldprice: 2500,
    Price: 2399,
    image: wearables6,
    sale: false,
    Bestseller: false,
    category: "Wearables",
    productInfo: "Sports Mode",
    description: "Fitness band for athletes.",
  },
  {
    id: 97,
    name: "SmartRing Lite",
    oldprice: 8000,
    Price: 7699,
    image: wearables7,
    sale: false,
    Bestseller: false,
    category: "Wearables",
    productInfo: "Sleep Tracking",
    description: "Smart ring with advanced sleep monitoring.",
  },
  {
    id: 98,
    name: "UltraWatch Max",
    oldprice: 12000,
    Price: 11499,
    image: wearables8,
    sale: false,
    Bestseller: true,
    category: "Wearables",
    productInfo: "AMOLED • Metal Body",
    description: "Premium smartwatch.",
  },
  // {
  //   id: 99,
  //   name: "WalkBand GO",
  //   oldprice: 1500,
  //   Price: 1399,
  //   image: "walkband-go.jpg",
  //   sale: false,
  //   Bestseller: false,
  //   category: "Wearables",
  //   productInfo: "Step Tracker",
  //   description: "Simple tracker for walking lovers.",
  // },
  // {
  //   id: 100,
  //   name: "FitPulse X",
  //   oldprice: 7000,
  //   Price: 6599,
  //   image: "fitpulse-x.jpg",
  //   sale: true,
  //   Bestseller: true,
  //   category: "Wearables",
  //   productInfo: "Fitness + ECG",
  //   description: "Top-end fitness smartwatch with ECG.",
  // },
];

export default ProductsData;
